repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: fix-encoding-pragma
      - id: detect-private-key
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: text-unicode-replacement-char
  # - repo: https://github.com/ScribeMD/pre-commit-hooks
  #   rev: 0.15.7
  #   hooks:
  #     - id: no-merge-commits
  #     - id: pre-commit-install
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: docker run -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --fail
        language: system
        stages: ["push"]
      - id: bash-config
        name: No file extensions starting with .bash
        entry: file extensions must not start with .bash
        language: fail
        files: '.*\.bash.*'
      - id: lint
        name: Run eslint via pnpm
        entry: pnpm run lint
        language: system
        pass_filenames: false
      # - id: test
      #   name: Run tests via pnpm
      #   entry: pnpm run test
      #   language: system
      #   pass_filenames: false
